import uuid
from datetime import datetime

from sqlalchemy import Column, DateTime, ForeignKey, String, Text, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db.session import Base


class RiskFactor(Base):
    __tablename__ = "risk_factors"
    
    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        default=uuid.uuid4,
    )
    
    report_id = Column(
        UUID(as_uuid=True),
        ForeignKey("analysis_reports.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # The risk description generated by the agent
    factor = Column(Text, nullable=False)
    
    severity = Column(String(10), nullable=False)
    
    # The specific claim the agent makes — gets verified in the verify node
    citation = Column(Text, nullable=False)

    source_chunk_id = Column(
        UUID(as_uuid=True),
        ForeignKey("filing_chunks.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    created_at = Column(DateTime, server_default=text("NOW()"), default=datetime.utcnow)
    
    report = relationship("AnalysisReport", back_populates="risk_factors")
    source_chunk = relationship("FilingChunk", back_populates="risk_factors")
    
    def __repr__(self):
        return f"<RiskFactor(id={self.id}, severity={self.severity}, factor={self.factor[:50]}...)>"