"""add created_at to filings and fix status default

Revision ID: 1b6a298363c1
Revises: 
Create Date: 2026-03-16 20:16:14.593000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6a298363c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    op.drop_index(op.f('ix_filings_ticket'), table_name='filings')
    op.create_index(op.f('ix_filings_ticker'), 'filings', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filings_ticker'), table_name='filings')
    op.create_index(op.f('ix_filings_ticket'), 'filings', ['ticker'], unique=False)
    op.drop_column('filings', 'created_at')
    # ### end Alembic commands ###
